import type { ActivityRecord, Company, Evidence, ReportingPeriod, Site, Source, SourceDocument } from "./index";
export interface DataIntakePersistence { saveCompany(v:Company):Promise<void>; getCompany(id:string):Promise<Company|null>; saveReportingPeriod(v:ReportingPeriod):Promise<void>; getReportingPeriod(c:string,p:string):Promise<ReportingPeriod|null>; saveSite(v:Site):Promise<void>; getSite(c:string,s:string):Promise<Site|null>; saveSource(v:Source):Promise<void>; saveDocument(v:SourceDocument):Promise<void>; getDocument(c:string,d:string):Promise<SourceDocument|null>; saveEvidence(v:Evidence):Promise<void>; saveActivity(v:ActivityRecord):Promise<ActivityRecord|null>; getActivity(c:string,id:string):Promise<ActivityRecord|null>; listActivities(c:string,p:string):Promise<ActivityRecord[]>; }
export class InMemoryDataIntakePersistence implements DataIntakePersistence {
 private companies=new Map<string,Company>(); private periods=new Map<string,ReportingPeriod>(); private sites=new Map<string,Site>(); private sources=new Map<string,Source>(); private documents=new Map<string,SourceDocument>(); private evidence=new Map<string,Evidence>(); private activities=new Map<string,ActivityRecord>(); private idempotency=new Map<string,string>();
 async saveCompany(v:Company){this.companies.set(v.companyId,v)} async getCompany(id:string){return this.companies.get(id)??null}
 async saveReportingPeriod(v:ReportingPeriod){this.periods.set(v.companyId+":"+v.periodId,v)} async getReportingPeriod(c:string,p:string){return this.periods.get(c+":"+p)??null}
 async saveSite(v:Site){this.sites.set(v.companyId+":"+v.siteId,v)} async getSite(c:string,s:string){return this.sites.get(c+":"+s)??null}
 async saveSource(v:Source){this.sources.set(v.sourceId,v)} async saveDocument(v:SourceDocument){this.documents.set(v.companyId+":"+v.documentId,v)} async getDocument(c:string,d:string){return this.documents.get(c+":"+d)??null}
 async saveEvidence(v:Evidence){this.evidence.set(v.evidenceId,v)} async saveActivity(v:ActivityRecord){const k=v.companyId+":"+v.idempotencyKey;const id=this.idempotency.get(k);if(id)return this.activities.get(id)??null;this.activities.set(v.activityId,v);this.idempotency.set(k,v.activityId);return null}
 async getActivity(c:string,id:string){const v=this.activities.get(id);return v?.companyId===c?v:null} async listActivities(c:string,p:string){return [...this.activities.values()].filter(v=>v.companyId===c&&v.reportingPeriodId===p)}
}